In [3]:
from itertools import permutations

import numpy as np

In [31]:
def transform_matrix(matrix, cube):
    transformed_cube = dict()
    for key in cube:
        transformed_cube[key] = list(matrix @ cube[key])
    return dict(
        sorted(transformed_cube.items(), key=lambda item: item[1])
    )

In [4]:
perm_matrices = []
for permutation in permutations([0, 1, 2]):
    m = np.zeros((3, 3))
    for row in range(3):
        m[row, permutation[row]] = 1
    perm_matrices.append(m)

In [5]:
perm_matrices

[array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]])]

In [6]:
cube = {
    "a": [0, 0, 0],
    "b": [0, 0, 1],
    "c": [0, 1, 0],
    "d": [0, 1, 1],
    "e": [1, 0, 0],
    "f": [1, 0, 1],
    "g": [1, 1, 0],
    "h": [1, 1, 1],
}

In [7]:
transform_matrix(perm_matrices[0], cube)

{'a': array([0., 0., 0.]),
 'b': array([0., 0., 1.]),
 'c': array([0., 1., 0.]),
 'd': array([0., 1., 1.]),
 'e': array([1., 0., 0.]),
 'f': array([1., 0., 1.]),
 'g': array([1., 1., 0.]),
 'h': array([1., 1., 1.])}

In [8]:
transform_matrix(perm_matrices[1], cube)

{'a': array([0., 0., 0.]),
 'c': array([0., 0., 1.]),
 'b': array([0., 1., 0.]),
 'd': array([0., 1., 1.]),
 'e': array([1., 0., 0.]),
 'g': array([1., 0., 1.]),
 'f': array([1., 1., 0.]),
 'h': array([1., 1., 1.])}

In [9]:
transform_matrix(perm_matrices[2], cube)

{'a': array([0., 0., 0.]),
 'b': array([0., 0., 1.]),
 'e': array([0., 1., 0.]),
 'f': array([0., 1., 1.]),
 'c': array([1., 0., 0.]),
 'd': array([1., 0., 1.]),
 'g': array([1., 1., 0.]),
 'h': array([1., 1., 1.])}

In [10]:
transform_matrix(perm_matrices[3], cube)

{'a': array([0., 0., 0.]),
 'e': array([0., 0., 1.]),
 'b': array([0., 1., 0.]),
 'f': array([0., 1., 1.]),
 'c': array([1., 0., 0.]),
 'g': array([1., 0., 1.]),
 'd': array([1., 1., 0.]),
 'h': array([1., 1., 1.])}

In [11]:
transform_matrix(perm_matrices[-1], cube)

{'a': array([0., 0., 0.]),
 'e': array([0., 0., 1.]),
 'c': array([0., 1., 0.]),
 'g': array([0., 1., 1.]),
 'b': array([1., 0., 0.]),
 'f': array([1., 0., 1.]),
 'd': array([1., 1., 0.]),
 'h': array([1., 1., 1.])}

In [39]:
r1=np.array([[1,0,0],
            [0,-1,0],
            [0,0,-1]])

r2=np.array([[-1,0,0],
            [0,1,0],
            [0,0,-1]])

r3=np.array([[-1,0,0],
            [0,-1,0],
            [0,0,1]])

cube2 = {
    "a": [-1, -1, -1],
    "b": [-1, -1, 1],
    "c": [-1, 1, -1],
    "d": [-1, 1, 1],
    "e": [1, -1, -1],
    "f": [1, -1, 1],
    "g": [1, 1, -1],
    "h": [1, 1, 1],
}

In [40]:
transform_matrix(np.eye(3), cube2)

{'a': [-1.0, -1.0, -1.0],
 'b': [-1.0, -1.0, 1.0],
 'c': [-1.0, 1.0, -1.0],
 'd': [-1.0, 1.0, 1.0],
 'e': [1.0, -1.0, -1.0],
 'f': [1.0, -1.0, 1.0],
 'g': [1.0, 1.0, -1.0],
 'h': [1.0, 1.0, 1.0]}

In [41]:
transform_matrix(r1, cube2)

{'d': [-1, -1, -1],
 'c': [-1, -1, 1],
 'b': [-1, 1, -1],
 'a': [-1, 1, 1],
 'h': [1, -1, -1],
 'g': [1, -1, 1],
 'f': [1, 1, -1],
 'e': [1, 1, 1]}

In [42]:
transform_matrix(r2, cube2)

{'f': [-1, -1, -1],
 'e': [-1, -1, 1],
 'h': [-1, 1, -1],
 'g': [-1, 1, 1],
 'b': [1, -1, -1],
 'a': [1, -1, 1],
 'd': [1, 1, -1],
 'c': [1, 1, 1]}

In [43]:
transform_matrix(r3, cube2)

{'g': [-1, -1, -1],
 'h': [-1, -1, 1],
 'e': [-1, 1, -1],
 'f': [-1, 1, 1],
 'c': [1, -1, -1],
 'd': [1, -1, 1],
 'a': [1, 1, -1],
 'b': [1, 1, 1]}