In [1]:
from itertools import permutations

import numpy as np

In [2]:
def transform_matrix(matrix, cube):
    transformed_cube = dict()
    for key in cube:
        transformed_cube[key] = list(matrix @ cube[key])
    return dict(sorted(transformed_cube.items(), key=lambda item: item[1]))

In [3]:
perm_matrices = []
for permutation in permutations([0, 1, 2]):
    m = np.zeros((3, 3))
    for row in range(3):
        m[row, permutation[row]] = 1
    perm_matrices.append(m)

In [4]:
perm_matrices

[array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]),
 array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]])]

In [5]:
cube = {
    "a": [0, 0, 0],
    "b": [0, 0, 1],
    "c": [0, 1, 0],
    "d": [0, 1, 1],
    "e": [1, 0, 0],
    "f": [1, 0, 1],
    "g": [1, 1, 0],
    "h": [1, 1, 1],
}

In [6]:
transform_matrix(perm_matrices[0], cube)

{'a': [0.0, 0.0, 0.0],
 'b': [0.0, 0.0, 1.0],
 'c': [0.0, 1.0, 0.0],
 'd': [0.0, 1.0, 1.0],
 'e': [1.0, 0.0, 0.0],
 'f': [1.0, 0.0, 1.0],
 'g': [1.0, 1.0, 0.0],
 'h': [1.0, 1.0, 1.0]}

In [7]:
transform_matrix(perm_matrices[1], cube)

{'a': [0.0, 0.0, 0.0],
 'c': [0.0, 0.0, 1.0],
 'b': [0.0, 1.0, 0.0],
 'd': [0.0, 1.0, 1.0],
 'e': [1.0, 0.0, 0.0],
 'g': [1.0, 0.0, 1.0],
 'f': [1.0, 1.0, 0.0],
 'h': [1.0, 1.0, 1.0]}

In [8]:
transform_matrix(perm_matrices[2], cube)

{'a': [0.0, 0.0, 0.0],
 'b': [0.0, 0.0, 1.0],
 'e': [0.0, 1.0, 0.0],
 'f': [0.0, 1.0, 1.0],
 'c': [1.0, 0.0, 0.0],
 'd': [1.0, 0.0, 1.0],
 'g': [1.0, 1.0, 0.0],
 'h': [1.0, 1.0, 1.0]}

In [9]:
transform_matrix(perm_matrices[3], cube)

{'a': [0.0, 0.0, 0.0],
 'e': [0.0, 0.0, 1.0],
 'b': [0.0, 1.0, 0.0],
 'f': [0.0, 1.0, 1.0],
 'c': [1.0, 0.0, 0.0],
 'g': [1.0, 0.0, 1.0],
 'd': [1.0, 1.0, 0.0],
 'h': [1.0, 1.0, 1.0]}

In [10]:
transform_matrix(perm_matrices[-1], cube)

{'a': [0.0, 0.0, 0.0],
 'e': [0.0, 0.0, 1.0],
 'c': [0.0, 1.0, 0.0],
 'g': [0.0, 1.0, 1.0],
 'b': [1.0, 0.0, 0.0],
 'f': [1.0, 0.0, 1.0],
 'd': [1.0, 1.0, 0.0],
 'h': [1.0, 1.0, 1.0]}

In [11]:
r1 = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]])

r2 = np.array([[-1, 0, 0], [0, 1, 0], [0, 0, -1]])

r3 = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]])

cube2 = {
    "a": [-1, -1, -1],
    "b": [-1, -1, 1],
    "c": [-1, 1, -1],
    "d": [-1, 1, 1],
    "e": [1, -1, -1],
    "f": [1, -1, 1],
    "g": [1, 1, -1],
    "h": [1, 1, 1],
}

In [12]:
transform_matrix(np.eye(3), cube2)

{'a': [-1.0, -1.0, -1.0],
 'b': [-1.0, -1.0, 1.0],
 'c': [-1.0, 1.0, -1.0],
 'd': [-1.0, 1.0, 1.0],
 'e': [1.0, -1.0, -1.0],
 'f': [1.0, -1.0, 1.0],
 'g': [1.0, 1.0, -1.0],
 'h': [1.0, 1.0, 1.0]}

In [13]:
transform_matrix(r1, cube2)

{'d': [-1, -1, -1],
 'c': [-1, -1, 1],
 'b': [-1, 1, -1],
 'a': [-1, 1, 1],
 'h': [1, -1, -1],
 'g': [1, -1, 1],
 'f': [1, 1, -1],
 'e': [1, 1, 1]}

In [14]:
transform_matrix(r2, cube2)

{'f': [-1, -1, -1],
 'e': [-1, -1, 1],
 'h': [-1, 1, -1],
 'g': [-1, 1, 1],
 'b': [1, -1, -1],
 'a': [1, -1, 1],
 'd': [1, 1, -1],
 'c': [1, 1, 1]}

In [15]:
transform_matrix(r3, cube2)

{'g': [-1, -1, -1],
 'h': [-1, -1, 1],
 'e': [-1, 1, -1],
 'f': [-1, 1, 1],
 'c': [1, -1, -1],
 'd': [1, -1, 1],
 'a': [1, 1, -1],
 'b': [1, 1, 1]}