In [1]:
import sympy as sp
from sympy.physics.quantum import TensorProduct
import numpy as np

# Define the symbols
x1, x2 = sp.symbols("x1 x2")

# Define the RZ matrices
RZ_x1 = sp.Matrix([[sp.exp(-sp.I * x1 / 2), 0], [0, sp.exp(sp.I * x1 / 2)]])
RZ_x2 = sp.Matrix([[sp.exp(-sp.I * x2 / 2), 0], [0, sp.exp(sp.I * x2 / 2)]])

# Compute the tensor product
RZ_tensor_product = TensorProduct(RZ_x1, RZ_x2)

In [2]:
RZ_tensor_product

Matrix([
[exp(-I*x1/2)*exp(-I*x2/2),                        0,                        0,                       0],
[                        0, exp(-I*x1/2)*exp(I*x2/2),                        0,                       0],
[                        0,                        0, exp(I*x1/2)*exp(-I*x2/2),                       0],
[                        0,                        0,                        0, exp(I*x1/2)*exp(I*x2/2)]])

In [3]:
TensorProduct(RZ_x2, RZ_x1)

Matrix([
[exp(-I*x1/2)*exp(-I*x2/2),                        0,                        0,                       0],
[                        0, exp(I*x1/2)*exp(-I*x2/2),                        0,                       0],
[                        0,                        0, exp(-I*x1/2)*exp(I*x2/2),                       0],
[                        0,                        0,                        0, exp(I*x1/2)*exp(I*x2/2)]])

In [4]:
swap = sp.Matrix([[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]])
swap

Matrix([
[1, 0, 0, 0],
[0, 0, 1, 0],
[0, 1, 0, 0],
[0, 0, 0, 1]])

In [5]:
swap * TensorProduct(RZ_x2, RZ_x1) * swap

Matrix([
[exp(-I*x1/2)*exp(-I*x2/2),                        0,                        0,                       0],
[                        0, exp(-I*x1/2)*exp(I*x2/2),                        0,                       0],
[                        0,                        0, exp(I*x1/2)*exp(-I*x2/2),                       0],
[                        0,                        0,                        0, exp(I*x1/2)*exp(I*x2/2)]])

In [6]:
X = sp.Matrix([[0, 1], [1, 0]])

In [7]:
X

Matrix([
[0, 1],
[1, 0]])

In [8]:
X * RZ_x1 * X

Matrix([
[exp(I*x1/2),            0],
[          0, exp(-I*x1/2)]])

In [9]:
RZ_x1

Matrix([
[exp(-I*x1/2),           0],
[           0, exp(I*x1/2)]])

In [10]:
a00, a01, a10, a11 = sp.symbols("a00 a01 a10 a11")
b00, b01, b02, b03, b10, b11, b12, b13, b20, b21, b22, b23, b30, b31, b32, b33 = (
    sp.symbols("b00 b01 b02 b03 b10 b11 b12 b13 b20 b21 b22 b23 b30 b31 b32 b33")
)
c00, c01, c10, c11 = sp.symbols("c00 c01 c10 c11")

# Define the matrices
A = sp.Matrix([[a00, a01], [a10, a11]])
B = sp.Matrix(
    [
        [b00, b01, b02, b03],
        [b10, b11, b12, b13],
        [b20, b21, b22, b23],
        [b30, b31, b32, b33],
    ]
)
C = sp.Matrix([[c00, c01], [c10, c11]])
B_small = sp.Matrix([[b00, b01], [b10, b11]])

# Compute the tensor (Kronecker) product of A and B
sp.kronecker_product(A, B)

Matrix([
[a00*b00, a00*b01, a00*b02, a00*b03, a01*b00, a01*b01, a01*b02, a01*b03],
[a00*b10, a00*b11, a00*b12, a00*b13, a01*b10, a01*b11, a01*b12, a01*b13],
[a00*b20, a00*b21, a00*b22, a00*b23, a01*b20, a01*b21, a01*b22, a01*b23],
[a00*b30, a00*b31, a00*b32, a00*b33, a01*b30, a01*b31, a01*b32, a01*b33],
[a10*b00, a10*b01, a10*b02, a10*b03, a11*b00, a11*b01, a11*b02, a11*b03],
[a10*b10, a10*b11, a10*b12, a10*b13, a11*b10, a11*b11, a11*b12, a11*b13],
[a10*b20, a10*b21, a10*b22, a10*b23, a11*b20, a11*b21, a11*b22, a11*b23],
[a10*b30, a10*b31, a10*b32, a10*b33, a11*b30, a11*b31, a11*b32, a11*b33]])

In [11]:
sp.kronecker_product(B, A)

Matrix([
[a00*b00, a01*b00, a00*b01, a01*b01, a00*b02, a01*b02, a00*b03, a01*b03],
[a10*b00, a11*b00, a10*b01, a11*b01, a10*b02, a11*b02, a10*b03, a11*b03],
[a00*b10, a01*b10, a00*b11, a01*b11, a00*b12, a01*b12, a00*b13, a01*b13],
[a10*b10, a11*b10, a10*b11, a11*b11, a10*b12, a11*b12, a10*b13, a11*b13],
[a00*b20, a01*b20, a00*b21, a01*b21, a00*b22, a01*b22, a00*b23, a01*b23],
[a10*b20, a11*b20, a10*b21, a11*b21, a10*b22, a11*b22, a10*b23, a11*b23],
[a00*b30, a01*b30, a00*b31, a01*b31, a00*b32, a01*b32, a00*b33, a01*b33],
[a10*b30, a11*b30, a10*b31, a11*b31, a10*b32, a11*b32, a10*b33, a11*b33]])

In [12]:
TensorProduct(A, B_small, C)

Matrix([
[a00*b00*c00, a00*b00*c01, a00*b01*c00, a00*b01*c01, a01*b00*c00, a01*b00*c01, a01*b01*c00, a01*b01*c01],
[a00*b00*c10, a00*b00*c11, a00*b01*c10, a00*b01*c11, a01*b00*c10, a01*b00*c11, a01*b01*c10, a01*b01*c11],
[a00*b10*c00, a00*b10*c01, a00*b11*c00, a00*b11*c01, a01*b10*c00, a01*b10*c01, a01*b11*c00, a01*b11*c01],
[a00*b10*c10, a00*b10*c11, a00*b11*c10, a00*b11*c11, a01*b10*c10, a01*b10*c11, a01*b11*c10, a01*b11*c11],
[a10*b00*c00, a10*b00*c01, a10*b01*c00, a10*b01*c01, a11*b00*c00, a11*b00*c01, a11*b01*c00, a11*b01*c01],
[a10*b00*c10, a10*b00*c11, a10*b01*c10, a10*b01*c11, a11*b00*c10, a11*b00*c11, a11*b01*c10, a11*b01*c11],
[a10*b10*c00, a10*b10*c01, a10*b11*c00, a10*b11*c01, a11*b10*c00, a11*b10*c01, a11*b11*c00, a11*b11*c01],
[a10*b10*c10, a10*b10*c11, a10*b11*c10, a10*b11*c11, a11*b10*c10, a11*b10*c11, a11*b11*c10, a11*b11*c11]])

In [13]:
aa = np.ones((2, 2))
bb = np.ones((2, 2))
cc = np.eye(2)
np.kron(np.kron(aa, bb), cc)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [14]:
bb = np.zeros((4, 4))
bb[0, 0] = bb[2, 1] = bb[1, 2] = bb[3, 3] = 1
np.kron(bb, np.eye(2))

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
bb

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [17]:
x = [[0, 1], [1, 0]]
i = [[1, 0], [0, 1]]
np.kron(np.kron(x, x), i)

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]])