In [1]:
import numpy as np
import sympy as sp
from sympy.physics.quantum import TensorProduct

# Define the symbols
x1, x2 = sp.symbols("x1 x2")

# Define the RZ matrices
RZ_x1 = sp.Matrix([[sp.exp(-sp.I * x1 / 2), 0], [0, sp.exp(sp.I * x1 / 2)]])
RZ_x2 = sp.Matrix([[sp.exp(-sp.I * x2 / 2), 0], [0, sp.exp(sp.I * x2 / 2)]])

# Compute the tensor product
RZ_tensor_product = TensorProduct(RZ_x1, RZ_x2)

In [1]:
import pennylane as qml

dev = qml.device("default.qubit", wires=1)


@qml.qnode(dev)
def apply_h_and_measure(state):
    """Complete the function such that we apply the Hadamard gate
    and measure in the computational basis.

    Args:
        state (int): Either 0 or 1. If 1, prepare the qubit in state |1>,
            otherwise leave it in state 0.

    Returns:
        np.array[float]: The measurement outcome probabilities.
    """
    if state == 1:
        qml.PauliX(wires=0)

    ##################
    # YOUR CODE HERE #
    ##################

    # APPLY HADAMARD AND MEASURE
    qml.Hadamard(0)
    return qml.state()


print(apply_h_and_measure(0))
print(apply_h_and_measure(1))

[0.70710678+0.j 0.70710678+0.j]
[ 0.70710678+0.j -0.70710678+0.j]


In [9]:
import pennylane as qml
from pennylane import X, Y, Z

dev = qml.device("default.qubit", wires=6)


@qml.qnode(dev)
def trotter():
    """Complete the function such that we apply the Hadamard gate
    and measure in the computational basis.

    Args:
        state (int): Either 0 or 1. If 1, prepare the qubit in state |1>,
            otherwise leave it in state 0.

    Returns:
        np.array[float]: The measurement outcome probabilities.
    """
    qml.TrotterProduct(
        0.5 * (X(0) @ X(1) @ X(2) @ Y(3) @ Z(5) @ X(4))
        - 0.5 * (X(0) @ X(1) @ X(2) @ Z(3) @ Y(5) @ X(4)),
        3,
    )
    return qml.state()


state = trotter()
sum([x * x.conj() for x in state])

(0.9999999999999997+0j)

In [13]:
import pennylane as qml
from pennylane import X, Y, Z

dev = qml.device("default.tensor", wires=6)


@qml.qnode(dev)
def trotter():
    """Complete the function such that we apply the Hadamard gate
    and measure in the computational basis.

    Args:
        state (int): Either 0 or 1. If 1, prepare the qubit in state |1>,
            otherwise leave it in state 0.

    Returns:
        np.array[float]: The measurement outcome probabilities.
    """
    qml.TrotterProduct(
        0.5 * (X(0) @ X(1) @ X(2) @ Y(3) @ Z(5) @ X(4))
        - 0.5 * (X(0) @ X(1) @ X(2) @ Z(3) @ Y(5) @ X(4)),
        2,
        2,
    )
    return qml.state()


state = trotter()
sum([x * x.conj() for x in state])

(1.0000000000000089+0j)

In [9]:
dev = qml.device("default.qubit", wires=2)
import numpy as np

H = 1 / np.sqrt(2) * np.array([[1, 1], [1, -1]])


@qml.qnode(dev)
def circuit():
    qml.Z(0)
    qml.X(1)
    return qml.state()

In [8]:
circuit()

array([0., 1., 0., 0.])

In [10]:
circuit()

array([ 0.+0.j,  1.+0.j, -0.+0.j, -0.+0.j])

In [2]:
RZ_tensor_product

Matrix([
[exp(-I*x1/2)*exp(-I*x2/2),                        0,                        0,                       0],
[                        0, exp(-I*x1/2)*exp(I*x2/2),                        0,                       0],
[                        0,                        0, exp(I*x1/2)*exp(-I*x2/2),                       0],
[                        0,                        0,                        0, exp(I*x1/2)*exp(I*x2/2)]])

In [3]:
TensorProduct(RZ_x2, RZ_x1)

Matrix([
[exp(-I*x1/2)*exp(-I*x2/2),                        0,                        0,                       0],
[                        0, exp(I*x1/2)*exp(-I*x2/2),                        0,                       0],
[                        0,                        0, exp(-I*x1/2)*exp(I*x2/2),                       0],
[                        0,                        0,                        0, exp(I*x1/2)*exp(I*x2/2)]])

In [4]:
swap = sp.Matrix([[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]])
swap

Matrix([
[1, 0, 0, 0],
[0, 0, 1, 0],
[0, 1, 0, 0],
[0, 0, 0, 1]])

In [5]:
swap * TensorProduct(RZ_x2, RZ_x1) * swap

Matrix([
[exp(-I*x1/2)*exp(-I*x2/2),                        0,                        0,                       0],
[                        0, exp(-I*x1/2)*exp(I*x2/2),                        0,                       0],
[                        0,                        0, exp(I*x1/2)*exp(-I*x2/2),                       0],
[                        0,                        0,                        0, exp(I*x1/2)*exp(I*x2/2)]])

In [6]:
X = sp.Matrix([[0, 1], [1, 0]])

In [7]:
X

Matrix([
[0, 1],
[1, 0]])

In [8]:
X * RZ_x1 * X

Matrix([
[exp(I*x1/2),            0],
[          0, exp(-I*x1/2)]])

In [9]:
RZ_x1

Matrix([
[exp(-I*x1/2),           0],
[           0, exp(I*x1/2)]])

In [10]:
a00, a01, a10, a11 = sp.symbols("a00 a01 a10 a11")
b00, b01, b02, b03, b10, b11, b12, b13, b20, b21, b22, b23, b30, b31, b32, b33 = (
    sp.symbols("b00 b01 b02 b03 b10 b11 b12 b13 b20 b21 b22 b23 b30 b31 b32 b33")
)
c00, c01, c10, c11 = sp.symbols("c00 c01 c10 c11")

# Define the matrices
A = sp.Matrix([[a00, a01], [a10, a11]])
B = sp.Matrix(
    [
        [b00, b01, b02, b03],
        [b10, b11, b12, b13],
        [b20, b21, b22, b23],
        [b30, b31, b32, b33],
    ]
)
C = sp.Matrix([[c00, c01], [c10, c11]])
B_small = sp.Matrix([[b00, b01], [b10, b11]])

# Compute the tensor (Kronecker) product of A and B
sp.kronecker_product(A, B)

Matrix([
[a00*b00, a00*b01, a00*b02, a00*b03, a01*b00, a01*b01, a01*b02, a01*b03],
[a00*b10, a00*b11, a00*b12, a00*b13, a01*b10, a01*b11, a01*b12, a01*b13],
[a00*b20, a00*b21, a00*b22, a00*b23, a01*b20, a01*b21, a01*b22, a01*b23],
[a00*b30, a00*b31, a00*b32, a00*b33, a01*b30, a01*b31, a01*b32, a01*b33],
[a10*b00, a10*b01, a10*b02, a10*b03, a11*b00, a11*b01, a11*b02, a11*b03],
[a10*b10, a10*b11, a10*b12, a10*b13, a11*b10, a11*b11, a11*b12, a11*b13],
[a10*b20, a10*b21, a10*b22, a10*b23, a11*b20, a11*b21, a11*b22, a11*b23],
[a10*b30, a10*b31, a10*b32, a10*b33, a11*b30, a11*b31, a11*b32, a11*b33]])

In [11]:
sp.kronecker_product(B, A)

Matrix([
[a00*b00, a01*b00, a00*b01, a01*b01, a00*b02, a01*b02, a00*b03, a01*b03],
[a10*b00, a11*b00, a10*b01, a11*b01, a10*b02, a11*b02, a10*b03, a11*b03],
[a00*b10, a01*b10, a00*b11, a01*b11, a00*b12, a01*b12, a00*b13, a01*b13],
[a10*b10, a11*b10, a10*b11, a11*b11, a10*b12, a11*b12, a10*b13, a11*b13],
[a00*b20, a01*b20, a00*b21, a01*b21, a00*b22, a01*b22, a00*b23, a01*b23],
[a10*b20, a11*b20, a10*b21, a11*b21, a10*b22, a11*b22, a10*b23, a11*b23],
[a00*b30, a01*b30, a00*b31, a01*b31, a00*b32, a01*b32, a00*b33, a01*b33],
[a10*b30, a11*b30, a10*b31, a11*b31, a10*b32, a11*b32, a10*b33, a11*b33]])

In [12]:
TensorProduct(A, B_small, C)

Matrix([
[a00*b00*c00, a00*b00*c01, a00*b01*c00, a00*b01*c01, a01*b00*c00, a01*b00*c01, a01*b01*c00, a01*b01*c01],
[a00*b00*c10, a00*b00*c11, a00*b01*c10, a00*b01*c11, a01*b00*c10, a01*b00*c11, a01*b01*c10, a01*b01*c11],
[a00*b10*c00, a00*b10*c01, a00*b11*c00, a00*b11*c01, a01*b10*c00, a01*b10*c01, a01*b11*c00, a01*b11*c01],
[a00*b10*c10, a00*b10*c11, a00*b11*c10, a00*b11*c11, a01*b10*c10, a01*b10*c11, a01*b11*c10, a01*b11*c11],
[a10*b00*c00, a10*b00*c01, a10*b01*c00, a10*b01*c01, a11*b00*c00, a11*b00*c01, a11*b01*c00, a11*b01*c01],
[a10*b00*c10, a10*b00*c11, a10*b01*c10, a10*b01*c11, a11*b00*c10, a11*b00*c11, a11*b01*c10, a11*b01*c11],
[a10*b10*c00, a10*b10*c01, a10*b11*c00, a10*b11*c01, a11*b10*c00, a11*b10*c01, a11*b11*c00, a11*b11*c01],
[a10*b10*c10, a10*b10*c11, a10*b11*c10, a10*b11*c11, a11*b10*c10, a11*b10*c11, a11*b11*c10, a11*b11*c11]])

In [13]:
aa = np.ones((2, 2))
bb = np.ones((2, 2))
cc = np.eye(2)
np.kron(np.kron(aa, bb), cc)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [14]:
bb = np.zeros((4, 4))
bb[0, 0] = bb[2, 1] = bb[1, 2] = bb[3, 3] = 1
np.kron(bb, np.eye(2))

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
bb

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [17]:
x = [[0, 1], [1, 0]]
i = [[1, 0], [0, 1]]
np.kron(np.kron(x, x), i)

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]])

In [8]:
from pyscf import gto, scf, fci
import numpy as np


def calculate_h2_energy(bond_length):
    # Define the H2 molecule with the given bond length
    mol = gto.Mole()
    mol.atom = f"""
    H 0 0 0
    H 0 0 {bond_length}
    """
    mol.basis = "def2-tzvp"  # Use a decent basis set, e.g., cc-pVDZ
    mol.unit = "Angstrom"
    mol.build()

    # Perform Hartree-Fock calculation
    mf = scf.RHF(mol)
    mf.kernel()

    # Perform FCI calculation
    cisolver = fci.FCI(mf)
    energy_fci = cisolver.kernel()[0]

    return energy_fci


# Range of bond lengths to explore (in Ångstroms)
bond_lengths = list(np.arange(0.01, 0.9, 0.1)) + list(np.arange(4.0, 5.0, 0.1))

# Calculate potential energy for each bond length
energies = []
for r in bond_lengths:
    energy = calculate_h2_energy(r)
    energies.append(energy)

# Print results
print("Bond Length (Å) | Potential Energy (Hartree)")
print("-" * 40)
for r, e in zip(bond_lengths, energies):
    print(f"{r:.3f}           | {e:.6f}")

converged SCF energy = 50.0950457093085
converged SCF energy = 2.08016564837038
converged SCF energy = -0.0501605868324431
converged SCF energy = -0.695064203180618
converged SCF energy = -0.955661774999085
converged SCF energy = -1.0699041023369
converged SCF energy = -1.11762237283538
converged SCF energy = -1.13207877889729
converged SCF energy = -1.12908668452757
converged SCF energy = -0.788130146082056
converged SCF energy = -0.785357630710914
converged SCF energy = -0.782782719493795
converged SCF energy = -0.780389617366233
converged SCF energy = -0.778163688503353
converged SCF energy = -0.776091380565421
converged SCF energy = -0.774160153904733
converged SCF energy = -0.772358415888274
converged SCF energy = -0.770675460091997
converged SCF energy = -0.769101409851691
Bond Length (Å) | Potential Energy (Hartree)
----------------------------------------
0.010           | 50.064746
0.110           | 2.048976
0.210           | -0.082536
0.310           | -0.728263
0.410        

In [9]:
from collections import namedtuple

# Define the namedtuple for B
B = namedtuple("B", ["C"])

# Create object A with an attribute B, which is a namedtuple
A = namedtuple("A", ["B"])

# Instantiate the object
A_instance = A(B(C=42))

# Accessing nested attributes
print(A_instance.B.C)  # Output: 42

42


In [12]:
A.B.C

AttributeError: '_collections._tuplegetter' object has no attribute 'C'